[workspace]
resolver = "2"
members = [
    "server",
    "client",
    "common",
    "commands",
    "discord_api",
]

[patch.crates-io]
pog_common = { path = "common" }
discord_api =  { path = "discord_api" }