version: '3.1'

services:
  db:
    image: postgres
    restart: always
#    network_mode: host
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: pog_server
      POSTGRES_USER: pog_user
      POSTGRES_PASSWORD: pog_pass
    volumes:
      - './db/migrations:/docker-entrypoint-initdb.d'