[package]
name = "pog_common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"]}
reqwest = { version = "0.11.22", default-features = false, features = ["rustls-tls","json"] }

[dev-dependencies]
serde_json = "1.0"